package MainForm;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rayleigh Thai
 */
public class e_customer extends javax.swing.JFrame {
    public e_customer() {
        initComponents();
        addb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infopane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        cmail = new javax.swing.JTextField();
        cphone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        bnew = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        booklist = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel6.setText("Phone");

        cid.setEditable(false);

        jLabel2.setText("Customer ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Email");

        addb.setText("Add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infopaneLayout = new javax.swing.GroupLayout(infopane);
        infopane.setLayout(infopaneLayout);
        infopaneLayout.setHorizontalGroup(
            infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(infopaneLayout.createSequentialGroup()
                        .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(infopaneLayout.createSequentialGroup()
                        .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addb))))
        );
        infopaneLayout.setVerticalGroup(
            infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infopaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infopaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addb))
                .addContainerGap())
        );

        clist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(clist);

        jLabel1.setText("Customer List:");

        bnew.setText("New");
        bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bdel.setText("Delete");
        bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(booklist);

        jLabel7.setText("Checkout");

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnew, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(bupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(refresh))
                            .addComponent(jScrollPane1))
                        .addGap(18, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infopane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infopane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdel)
                    .addComponent(bupdate)
                    .addComponent(bnew)
                    .addComponent(backbutton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void fclose(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        fclose();
        guiemployee back = new guiemployee();
        back.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed
    public void refresh(){
      try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root","");
            String query = "select * from customer";
            Statement sta = connection.createStatement();
            ResultSet rs = sta.executeQuery(query);  
            DefaultListModel customer = new DefaultListModel();
            while (rs.next()) {
                customer.addElement(rs.getString("c_id") + " - " + rs.getString("c_name"));
            }
            clist.setModel(customer);
            connection.close();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
 
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_refreshActionPerformed
    
    public void checkbook(String id) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
            String query = "Select * from book as b join checkout as c on b.b_id = c.b_id join customer as cc on c.c_id = cc.c_id where cc.c_id = " + id;
            Statement sta = connection.createStatement();
            ResultSet rs = sta.executeQuery(query);
            DefaultListModel book = new DefaultListModel();
            while (rs.next()) {
                book.addElement(rs.getString("return_date") +" with " + rs.getString("b_name") + " by "+ rs.getString("b_author"));
            }
            System.out.println("Get books checked for " + id );
            booklist.setModel(book);
            connection.close();
        } catch (Exception exception) { //catch any exceptions that may have occured
            exception.printStackTrace(); //print any errors
        }
    }
    
    public void getinfo(String id) {
        System.out.println(id);
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
            String query = "Select * from customer where c_id = " + id;
            Statement sta = connection.createStatement();
            ResultSet rs = sta.executeQuery(query);
            while (rs.next()) {
                //Set the controls to the dtabase values
                cid.setText(rs.getString("c_id"));
                String name = rs.getString("c_name");
                String[] str = name.split(" ");
                String first = str[0];
                fname.setText(first);
                String last = str[1];
                lname.setText(last);
                cphone.setText(rs.getString("c_phone"));
                cmail.setText(rs.getString("c_email"));
                checkbook(id);
            }
            System.out.println("Get infor for " + id );
            connection.close();
        } catch (Exception exception) { //catch any exceptions that may have occured
            exception.printStackTrace(); //print any errors
        }
    }
    
    private void clistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clistValueChanged
        int index = clist.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        if (index >= 0) {
            String s = (String) clist.getSelectedValue();
            String[] str = s.split(" - ");
            String id = str[0].trim();
            getinfo(id);
        }
    }//GEN-LAST:event_clistValueChanged

    private void bnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewActionPerformed
        cid.setText("");
        fname.setText("");
        lname.setText("");
        cphone.setText("");
        cmail.setText("");
        addb.setVisible(true);
    }//GEN-LAST:event_bnewActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        String name = fname.getText() + " " + lname.getText();
        System.out.println("+"+name+ "+");
        String mail = cmail.getText();
        String phone = cphone.getText();
        int check;
        if (phone.equals("")){
            check =0; 
            System.out.println(check);
        }
        else{
            check = Integer.parseInt(phone);
        }
        
        if (fname.getText().equals("") || lname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Need First name and Last Name insert here.");
        }
        else if (check == (int)check) {
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
                String query = "Select max(c_id) from customer";
                Statement sta = connection.createStatement();
                ResultSet rs = sta.executeQuery(query);
                int nuserid = 0;
                while (rs.next()) {
                    System.out.println("hereasdf");
                    nuserid = rs.getInt("max(c_id)") + 1;
                }
                System.out.println("New id = " +nuserid);
                String insert = "Insert into customer values("+ nuserid+ ", \""+ name +"\", \""+ check + "\", \""+ mail+ "\")" ;
                System.out.println(insert);
                sta.executeUpdate(insert);
                JOptionPane.showMessageDialog(this, "New entry added!");
                addb.setVisible(false);
                //close the connection
                connection.close();
                refresh();
            } catch (Exception exception) { //catch any exceptions that may have occured
                exception.printStackTrace(); //print any errors
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Phone number either blank or numberic.");
        }
    }//GEN-LAST:event_addbActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        String id = cid.getText();
        String name = fname.getText() + " " + lname.getText();
        System.out.println("+"+name+ "+");
        String mail = cmail.getText();
        String phone = cphone.getText();
        double check;
        if (phone.equals("")){
            check =0; 
            System.out.println(check);
        }
        else{
            System.out.println("asfdjas");
            check = Double.parseDouble(phone);
        }
        if (check == (double)check) {
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
                Statement sta = connection.createStatement();
                String insert = "update customer set c_name= \"" + name +
                        "\", c_phone= \"" + phone +
                        "\", c_email= \""+ mail + "\" where c_id = " + id ;
                System.out.println(insert);
                sta.executeUpdate(insert);
                JOptionPane.showMessageDialog(this, "Entry Updated!");
                addb.setVisible(false);
                connection.close();
                refresh();
            } catch (Exception exception) { //catch any exceptions that may have occured
                exception.printStackTrace(); //print any errors
            }
        }      
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
        String duserid = cid.getText();
        DefaultListModel book = (DefaultListModel) booklist.getModel();
        if (duserid.equals("")) {
            JOptionPane.showMessageDialog(this, "Select User");
        }
        if (book.getSize() > 0) {
            JOptionPane.showMessageDialog(this,"Failed to Delete user until Book(s) returns!");
        }        
        else {
            try {
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");              
                Statement sta = connection.createStatement();
                String str = "DELETE FROM `customer` WHERE c_id = " + duserid;
                System.out.println(str);
                sta.executeUpdate(str);
                JOptionPane.showMessageDialog(this, "Deletion success!");
                
                refresh();
                connection.close();
            } catch (Exception exception) {
                exception.printStackTrace();
            }  
        }
    }//GEN-LAST:event_bdelActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(e_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(e_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(e_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(e_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new e_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton bdel;
    private javax.swing.JButton bnew;
    private javax.swing.JList<String> booklist;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField cid;
    private javax.swing.JList<String> clist;
    private javax.swing.JTextField cmail;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel infopane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lname;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
