package MainForm;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rayleigh Thai
 */
public class linquiry extends javax.swing.JFrame {
    public linquiry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        belist = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        bnlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        vnt = new javax.swing.JTextField();
        vat = new javax.swing.JTextField();
        vpt = new javax.swing.JTextField();
        refreshb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        balist = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        addb = new javax.swing.JButton();
        order = new javax.swing.JButton();
        rmvb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backb.setText("Back");
        backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(belist);

        bnlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bnlistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(bnlist);

        jLabel1.setText("Book exists in Library");

        jLabel2.setText("Books not in Library");

        jLabel3.setText("Vendor Info");

        jLabel4.setText("ID");

        jLabel5.setText("Name: ");

        jLabel6.setText("Address: ");

        jLabel7.setText("Phone #: ");

        vid.setEditable(false);

        refreshb.setText("Refresh");
        refreshb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(balist);

        jLabel8.setText("Books Adding to Library");

        addb.setText("Add Books to Library");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        order.setText("Process Order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });

        rmvb.setText("Remove Selection");
        rmvb.setToolTipText("");
        rmvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addb))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refreshb)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vnt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vat)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(vpt, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rmvb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(order)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(refreshb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addb)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backb)
                    .addComponent(order)
                    .addComponent(rmvb))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fclose(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        fclose();
        guimanager back = new guimanager();
        back.setVisible(true);
    }//GEN-LAST:event_backbActionPerformed

    public void refresh() {
        inlibre();
        notlibre();
    }
    
    public void inlibre() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root","");
            String bquery = "Select * from book where exist_in_database = 1 order by b_name";
            Statement sta = connection.createStatement();
            ResultSet bs = sta.executeQuery(bquery);
            DefaultListModel book = new DefaultListModel();
            while (bs.next()) {
                book.addElement(bs.getString("b_id") + " - " + bs.getString("b_name"));
            }
            belist.setModel(book);
            connection.close();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
    
    public void notlibre() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root","");
            String bquery = "Select * from book where exist_in_database = 0 order by b_name";
            Statement sta = connection.createStatement();
            ResultSet bs = sta.executeQuery(bquery);
            DefaultListModel book = new DefaultListModel();
            while (bs.next()) {
                book.addElement(bs.getString("b_id") + " - " + bs.getString("b_name"));
            }
            bnlist.setModel(book);
            connection.close();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
    
    private void refreshbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbActionPerformed
        refresh();
    }//GEN-LAST:event_refreshbActionPerformed

    private void bnlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bnlistValueChanged
        int index = bnlist.getSelectedIndex();
        if(index >= 0) {
            String s = (String) bnlist.getSelectedValue();
            String[] str = s.split(" - ");
            String id = str[0].trim();
            String bn = str[1].trim();
            getvinfo(id, bn);
            System.out.println(index);
        }
    }//GEN-LAST:event_bnlistValueChanged
    
    void getvinfo(String id, String name) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
            String query = "Select * from book where b_id = \"" + id + "\" and b_name = \""+name+"\"";
            Statement sta = connection.createStatement();
            ResultSet rs = sta.executeQuery(query);
            while (rs.next()) {
                getinfo(rs.getString("v_id"));
            }
            System.out.println("Get infor for " + id );
            connection.close();
        } catch (Exception exception) { //catch any exceptions that may have occured
            exception.printStackTrace(); //print any errors
        }
    }
    void getinfo(String id) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root", "");
            String query = "Select * from vendor where v_id = " + id;
            Statement sta = connection.createStatement();
            ResultSet rs = sta.executeQuery(query);
            while (rs.next()) {
                System.out.println("Herer");
                vid.setText(rs.getString("v_id"));
                vnt.setText(rs.getString("v_name"));
                vat.setText(rs.getString("v_address"));
                vpt.setText(rs.getString("v_phone"));
            }
            System.out.println("Get infor for " + id );
            connection.close();
        } catch (Exception exception) { //catch any exceptions that may have occured
            exception.printStackTrace(); //print any errors
        }
    }
    
    DefaultListModel bre = new DefaultListModel();
    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        String s = (String) bnlist.getSelectedValue();
        System.out.println(s);
        int i = bre.getSize();
        while (i > 0) {
            if (s.equals(bre.getElementAt(i-1).toString())) {
                bre.removeElementAt(i-1);
                System.out.println("Not Removing");
                JOptionPane.showMessageDialog(this, "This Book already in the List!");
            }
            i--;
        }
        bre.addElement(s);
        balist.setModel(bre);
    }//GEN-LAST:event_addbActionPerformed

    private void rmvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvbActionPerformed
        int index = balist.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        DefaultListModel rm = (DefaultListModel) balist.getModel();
        if (index >= 0) {
            rm.removeElementAt(index);
            balist.setModel(rm);
            JOptionPane.showMessageDialog(this, "Selection was removed!");
        }
        else {
            JOptionPane.showMessageDialog(this, "No Selection was selected!");
        }
    }//GEN-LAST:event_rmvbActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        DefaultListModel returning = (DefaultListModel) balist.getModel();
        int i = returning.getSize(); 
        while (i > 0) {
            String index = returning.getElementAt(i-1).toString();
            String[] s = index.split(" - ");
            String id = s[0].trim();
            String name = s[1].trim();
            returning.removeElementAt(i-1);
            String stm = "Update book set exist_in_database = 1 where b_id = \"" + id + "\" and b_name = \"" + name + "\"";
            System.out.println(stm);
            bupdate(stm);
            i--;
        }
        JOptionPane.showMessageDialog(this, "Book(s) added to library");
        balist.setModel(returning);
        refresh();
    }//GEN-LAST:event_orderActionPerformed
    void bupdate(String stm) {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/number_1", "root","");
            Statement sta = connection.createStatement();
            sta.executeUpdate(stm); 
            connection.close();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(linquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(linquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(linquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(linquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new linquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JButton backb;
    private javax.swing.JList<String> balist;
    private javax.swing.JList<String> belist;
    private javax.swing.JList<String> bnlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton order;
    private javax.swing.JButton refreshb;
    private javax.swing.JButton rmvb;
    private javax.swing.JTextField vat;
    private javax.swing.JTextField vid;
    private javax.swing.JTextField vnt;
    private javax.swing.JTextField vpt;
    // End of variables declaration//GEN-END:variables
}
